// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6SpiatidapjqyvJlnhRQ6N2jX81K5DY',
    appId: '1:132950112983:web:cfd995b5bd25fb08c84e92',
    messagingSenderId: '132950112983',
    projectId: 'alora-b477f',
    authDomain: 'alora-b477f.firebaseapp.com',
    storageBucket: 'alora-b477f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLMYdRz07snb1PfFGj8XBJaZ_Nb4ttlc',
    appId: '1:132950112983:android:4ab50f02b9d7b218c84e92',
    messagingSenderId: '132950112983',
    projectId: 'alora-b477f',
    storageBucket: 'alora-b477f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLusR13ve6imRJKzB9EFiFtnzJuvC49U',
    appId: '1:132950112983:ios:f1dfc14af3b42cf9c84e92',
    messagingSenderId: '132950112983',
    projectId: 'alora-b477f',
    storageBucket: 'alora-b477f.appspot.com',
    iosClientId: '132950112983-5e9vtdkmegn7ufjk7ckbl7j77fr5mbdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.alora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLusR13ve6imRJKzB9EFiFtnzJuvC49U',
    appId: '1:132950112983:ios:f1dfc14af3b42cf9c84e92',
    messagingSenderId: '132950112983',
    projectId: 'alora-b477f',
    storageBucket: 'alora-b477f.appspot.com',
    iosClientId: '132950112983-5e9vtdkmegn7ufjk7ckbl7j77fr5mbdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.alora',
  );
}
