// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6SpiatidapjqyvJlnhRQ6N2jX81K5DY',
    appId: '1:132950112983:web:cfd995b5bd25fb08c84e92',
    messagingSenderId: '132950112983',
    projectId: 'alora-b477f',
    authDomain: 'alora-b477f.firebaseapp.com',
    storageBucket: 'alora-b477f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0QmafJhR4WqfmhFyJxwGZwwgUeYhIW8',
    appId: '1:348068762787:android:3a2d02458ceed41d551b16',
    messagingSenderId: '348068762787',
    projectId: 'greenagain-7902a',
    storageBucket: 'greenagain-7902a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUvgXydP_2Irz4YtjJFD_k_esFETLG0A',
    appId: '1:348068762787:ios:ba8bf8ba1bed2b4f551b16',
    messagingSenderId: '348068762787',
    projectId: 'greenagain-7902a',
    storageBucket: 'greenagain-7902a.appspot.com',
    iosBundleId: 'com.mysdgsdockta.app',
  );

}